### ISSUE TITLE
求助：ss-libev+ss-manager+ss-webgui不能工作，似乎manager api没启成功

### ISSUE THREAD

**Issue by luggie1** [shadowsocks/shadowsocks-libev#1561]
步骤如下：
1.安装shadowsocks-libev，用ss-server启动成功，且客户端连接该服务可正常使用；
2.安装shadowsocks-manager
4.启动ss-manager：
   # ss-manager -m aes-256-cfb -u --manager-address 127.0.0.1:6001
       2017-07-10 19:39:07 INFO: running from root user

5.创建ss.yml,内容如下：
type: s
empty: false
shadowsocks:
  address: 127.0.0.1:6001
manager:
  address: 0.0.0.0:4001
  password: 'xxxxxx'
db: 'ss.sqlite'
然后，启动：
# ssmgr -c ss.yml 
/node-v6.11.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/
[2017-07-10 19:42:35.325] [INFO] system - System start.

6.创建webgui.yml,内容如下：
type: m
empty: false

manager:
  address: 公网地址:4001
  password: 'xxxxxx'
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
    pay:
      hour:
        price: 0.03
        flow: 500000000
      day:
        price: 0.5
        flow: 7000000000
      week:
        price: 3
        flow: 50000000000
      month:
        price: 10
        flow: 200000000000
      season:
        price: 30
        flow: 200000000000
      year:
        price: 120
        flow: 200000000000
  email:
    use: true
    username: 'xxx'
    password: 'xxx'
    host: 'xxx'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'http://xxx'
    gcmSenderId: 'xxx'
    gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
  alipay:
    use: true
    appid: 2015012108272442
    notifyUrl: 'http://yourwebsite.com/api/user/alipay/callback'
    merchantPrivateKey: 'xxxxxxxxxxxx'
    alipayPublicKey: 'xxxxxxxxxxx'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'

db: 'webgui.sqlite'
然后，启动：
# ssmgr -c webgui.yml
/node-v6.11.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/
[2017-07-10 19:47:33.702] [INFO] system - System start.
然后接着报如下错误：
 [ERROR] account - Error: ssmgr[s] connection close  [公网地址:4001]
    at Socket.client.on (/node-v6.11.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/services/manager.js:93:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)
[2017-07-10 19:51:00.022] [ERROR] flowSaver - Error: ssmgr[s] connection close  [公网地址:4001]
    at Socket.client.on (/node-v6.11.0-linux-x64/lib/node_modules/shadowsocks-manager/lib/services/manager.js:93:14)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)

麻烦帮忙看看，是哪里出问题了？万分感谢！
（webgui可以正常访问，但管理员添加新服务器不成功，应该也是上面原因导致）

**Comment by madeye** [comment]
It looks a configuration issue of ssmgr. Post your issue here instead: https://github.com/shadowsocks/shadowsocks-manager

**Comment by luggie1** [comment]
thank you!
