### ISSUE TITLE
Denial-of-Service vulnerability in json.c json_parse_ex through nullptr deref

### ISSUE THREAD

**Issue by felixgr** [shadowsocks/shadowsocks-libev#1594]
I'm currently working on fuzzing shadowsocks-libev. It would be nice to have shadowsocks in OSS Fuzz… if you have interest in getting that: let me know.

I found a minor Denial-of-Service vulnerability in json_parse_ex through nullptr dereference. The function seems to be reachable in the manager via parse_traffic for unauthenticated users.

I'm using git 556627399eea90f35feb998b38c66cf3c571ce09 on Linux.

json_fuzz.c:

```c
/* Add to src/Makefile.am:
 bin_PROGRAMS += json_fuzz
 json_fuzz_SOURCES = json_fuzz.c json.c utils.c
 json_fuzz_CFLAGS = $(AM_CFLAGS)
 json_fuzz_LDADD = $(SS_COMMON_LIBS)
 json_fuzz_LDADD += -ludns
*/
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include "json.h"
#include "protocol.h"

int main(int argc, char **argv) {
  char *buf = NULL;
  size_t len = 0;
  FILE *fp = fopen(argv[1], "r");
  if (fp != NULL) {
      if (fseek(fp, 0L, SEEK_END) == 0) {
          long bufsize = ftell(fp);
          if (bufsize == -1) {
            return 0;
          }

          buf = malloc(sizeof(char) * (bufsize + 1));

          if (fseek(fp, 0L, SEEK_SET) != 0) {
            return 0;
          }

          len = fread(buf, sizeof(char), bufsize, fp);
          if ( ferror( fp ) != 0 ) {
              fputs("Error reading file", stderr);
              return 0;
          }
      }
      fclose(fp);
  }

  if (len < 30) {
    free(buf);
    return 0;
  }

  char error_buf[512];
  json_settings settings = { 0 };
  json_value *obj = json_parse_ex(&settings, buf, len, error_buf);

  if (obj != NULL) {
    json_value_free(obj);
  }
  free(buf);

  printf("parsed %zx bytes\n", len);
  return 0;
}
```

Use this file as input:

```
$ printf '\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n]ooo\n' > repro
$ ./src/json_fuzz repro
```

Repro:

```
==19991==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x000000402a27 bp 0x7ffd924427f0 sp 0x7ffd924424e0 T0)
==19991==The signal is caused by a READ memory access.
==19991==Hint: address points to the zero page.
    #0 0x402a26 in json_parse_ex shadowsocks-libev/src/json.c:520:30
    #1 0x401eeb in main shadowsocks-libev/src/json_fuzz.c:41:21
    #2 0x7f361b5f3f44 in __libc_start_main /build/eglibc-SvCtMH/eglibc-2.19/csu/libc-start.c:287
    #3 0x401ab8 in _start (shadowsocks-libev/afl/debug/json_fuzz+0x401ab8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV shadowsocks-libev/src/json.c:520:30 in json_parse_ex
```

**Comment by madeye** [comment]
Is it possible to open a pull request for this?

**Comment by madeye** [comment]
Fixed by updating json.c to the latest. Tested on macOS 10.12.2.

Could you help to verify the fix in your environment?

**Comment by felixgr** [comment]
Sure, I'll verify tomorrow

**Comment by felixgr** [comment]
Verified fix. I'll create a PR for the fuzzers when I'm finished with the project. Is there general interest by the project to get on OSS Fuzz? https://github.com/google/oss-fuzz

**Comment by madeye** [comment]
Yes, please open a PR when the fuzzers are ready.
