### ISSUE TITLE
Can't connect server once I've changed shadowsocks-python to shadowsocks-libev 

### ISSUE THREAD

**Issue by FlandiaYingman** [shadowsocks/shadowsocks-libev#2199]
### What version of shadowsocks-libev are you using?
I've just installed from apt-get, it may be 3.2.0

### What operating system are you using?
Ubuntu 18.10 x64

### What did you do?
I installed shadowsocks-libev from apt-get, configured the configurations, and then I started the server: `sudo /etc/init.d/shadowsocks-libev start`

### What did you expect to see?
I want to connect to my server.

### What did you see instead?
Error logs on client:
```
[2018-10-19 23:14:26] System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it
   at Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   at Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   at Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
```
and
```
[2018-10-19 23:15:07] [my server ip]:12345 timed out
```

### What is your config in detail (with all sensitive info masked)?
```
{
    "server":"127.0.0.1",
    "server_port":12345,
    "local_port":1080,
    "password":"987654321",
    "timeout":"60"
    "method":"salsa20"
}
```

Thanks in advance

---

I used tcping to ping it, it has no response.

**Comment by FlandiaYingman** [comment]
Fixed: server to **0.0.0.0**
```
{
    "server":"0.0.0.0",
    "server_port":12345,
    "local_port":1080,
    "password":"987654321",
    "timeout":"60"
    "method":"salsa20"
}
```
