### ISSUE TITLE
ss-manager Reboots Port with shadowsocks-manager Unexpectedly and Repeatedly

### ISSUE THREAD

**Issue by RebelliousWhiz** [shadowsocks/shadowsocks-libev#2658]
### What version of shadowsocks-libev are you using?
3.3.4

### What operating system are you using?
ubuntu 18.04.4

### What did you do?
shadowsocks-manager webgui up and running with ss-manager, normally without any problem.

server.hk1 is running webgui with MySQL, server.hk2 and server.hk3 connected to the server1 with webgui.

Set up a port 18600 in the webgui (through the admin page, create an account), grant unlimited data.

Devices connect to server.hk2 port 18600, daily data usage around 3GB according to webgui.

### What did you expect to see?
Port 18600 running without any unexpected problems.

### What did you see instead?
Every once a while, port 18600 is rebooted by ss-manager. It's causing problems because it has been many times I am in a meeting using shadowsocks, and the meeting freezes unexpectedly and has to switch from hk2 to hk3. But both server ports can be rebooted every once a while. Have to switch hk3 to hk2 back and forth (I only use hk2 and hk3 for work).

![image text](https://raw.githubusercontent.com/RebelliousWhiz/imagecaches/master/photo6285171797582260518.jpg)

![image text](https://raw.githubusercontent.com/RebelliousWhiz/imagecaches/master/photo6287423597395945885.jpg)

I have talked to shadowsocks-manager maintainer @gyteng, and he suggested me to use shadowsocks python version. I haven't tested on python yet, and I prefer not to because I am more familiar with shadowsocks-libev than python shadowsocks. Plus, I believe it is a bug.

### What is your config in detail (with all sensitive info masked)?

**server.hk1**

ss-manager -c /home/user/server/ss-manager/config.json --manager-address 127.0.0.1:2000

```
{
    "timeout":60,
    "method":"aes-256-gcm",
    "mode":"tcp_and_udp"
}
```

ssmgr -c /home/user/server/ssmgr/ssmgr.json

```
{
  "type": "s",
  "shadowsocks": {
    "address": "127.0.0.1:2000"
  },
  "manager": {
    "address": "0.0.0.0:xxxxx",
    "password": "password"
  },
  "db": "db.sqlite"
}
```

ssmgr -c /home/user/server/ssmgr/webgui.json

```
{
  "type": "m",
  "manager": {
    "address": "127.0.0.1:xxxxxx",
    "password": "password"
  },
  "plugins": {
    "flowSaver": {
      "use": true
    },
    "user": {
      "use": true
    },
    "account": {
      "use": true
    },
    "email": {
      "use": true,
      "type": "smtp",
      "username": "myemail@email",
      "password": "emailpass",
      "host": "smtp.office365.com",
      "port": "587",
      "secure": false
    },
    "webgui": {
      "use": true,
      "host": "0.0.0.0",
      "port": "xxxx",
      "admin_username": "myemal@email",
      "admin_password": "myemailpass",
      "skin": "myskin",
      "language": "en-US",
      "site": "mysiteaddress"
    },
    "paypal": {
      "use": true,
      "mode": "sandbox",
      "client_id": "id",
      "client_secret": "secret"
    },
    "giftcard": {
      "use": true
    }
  },
  "db": {
    "host": "127.0.0.1",
    "port": "xxxx",
    "user": "myuser",
    "password": "mypasword",
    "database": "mydatabase"
  },
  "redis": {
    "host": "127.0.0.1",
    "port": xxxx,
    "password": "myredis pass",
    "db": 0
  }
}
```

**server.hk2 and server.hk3**

ss-manager -c /home/user/server/ss-manager/config.json --manager-address 127.0.0.1:2000

```
{
    "timeout":60,
    "method":"aes-256-gcm",
    "mode":"tcp_and_udp"
}
```

ssmgr -c /home/user/server/ssmgr/ssmgr.json

```
{
  "type": "s",
  "shadowsocks": {
    "address": "127.0.0.1:2000"
  },
  "manager": {
    "address": "0.0.0.0:xxxxx",
    "password": "password"
  },
  "db": "db.sqlite"
}
```

**Comment by RebelliousWhiz** [comment]
Here's how frequently the ss-manager restarts the port:

**server.hk2**

```
journalctl -u ss-manager --since "2020-03-10" | grep "try to bind"
Mar 10 00:57:00 hk2 ss-manager[15395]:  2020-03-10 00:57:00 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 10 08:31:00 hk2 ss-manager[15395]:  2020-03-10 08:30:59 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 10 08:33:00 hk2 ss-manager[15395]:  2020-03-10 08:32:59 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 10 08:34:00 hk2 ss-manager[15395]:  2020-03-10 08:33:59 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 10 08:35:00 hk2 ss-manager[15395]:  2020-03-10 08:34:59 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 10 08:36:00 hk2 ss-manager[15395]:  2020-03-10 08:36:00 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 10 08:38:00 hk2 ss-manager[15395]:  2020-03-10 08:37:59 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 10 08:39:00 hk2 ss-manager[15395]:  2020-03-10 08:38:59 INFO: try to bind interface: 0.0.0.0, port: 18600
..................(endless)...
Mar 14 12:43:00 hk2 ss-manager[4706]:  2020-03-14 12:42:59 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 14 13:04:06 hk2 ss-manager[22783]:  2020-03-14 13:04:06 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 14 13:04:20 hk2 ss-manager[23289]:  2020-03-14 13:04:20 INFO: try to bind interface: 0.0.0.0, port: 18600
```

And also, the server.hk1 is getting a similar log since a few days ago I invited a few friends to use my server it has similar behavior but much less than the server.hk1:

**server.hk1**

```
journalctl -u ss-manager --since "2020-03-10" | grep "try to bind"
Mar 13 16:30:46 hk1 ss-manager[20994]:  2020-03-13 16:30:46 INFO: try to bind interface: 0.0.0.0, port: 17802
Mar 13 16:52:00 hk1 ss-manager[20994]:  2020-03-13 16:52:00 INFO: try to bind interface: 0.0.0.0, port: 15624
Mar 13 20:01:00 hk1 ss-manager[20994]:  2020-03-13 20:01:00 INFO: try to bind interface: 0.0.0.0, port: 17802
Mar 13 20:02:00 hk1 ss-manager[20994]:  2020-03-13 20:02:00 INFO: try to bind interface: 0.0.0.0, port: 17802
Mar 13 22:55:00 hk1 ss-manager[20994]:  2020-03-13 22:55:00 INFO: try to bind interface: 0.0.0.0, port: 15624
Mar 13 22:56:00 hk1 ss-manager[20994]:  2020-03-13 22:56:00 INFO: try to bind interface: 0.0.0.0, port: 15624
Mar 13 23:06:00 hk1 ss-manager[20994]:  2020-03-13 23:06:00 INFO: try to bind interface: 0.0.0.0, port: 16385
Mar 13 23:07:00 hk1 ss-manager[20994]:  2020-03-13 23:07:00 INFO: try to bind interface: 0.0.0.0, port: 16385
Mar 14 00:34:00 hk1 ss-manager[20994]:  2020-03-14 00:34:00 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 14 00:47:00 hk1 ss-manager[20994]:  2020-03-14 00:47:00 INFO: try to bind interface: 0.0.0.0, port: 15624
Mar 14 00:48:00 hk1 ss-manager[20994]:  2020-03-14 00:48:00 INFO: try to bind interface: 0.0.0.0, port: 15624
Mar 14 01:35:00 hk1 ss-manager[20994]:  2020-03-14 01:35:00 INFO: try to bind interface: 0.0.0.0, port: 15624
Mar 14 01:36:00 hk1 ss-manager[20994]:  2020-03-14 01:36:00 INFO: try to bind interface: 0.0.0.0, port: 15624
Mar 14 01:57:00 hk1 ss-manager[20994]:  2020-03-14 01:57:00 INFO: try to bind interface: 0.0.0.0, port: 17219
Mar 14 02:54:00 hk1 ss-manager[20994]:  2020-03-14 02:54:00 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 14 07:42:00 hk1 ss-manager[20994]:  2020-03-14 07:42:00 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 14 07:43:00 hk1 ss-manager[20994]:  2020-03-14 07:43:00 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 14 10:16:00 hk1 ss-manager[20994]:  2020-03-14 10:16:00 INFO: try to bind interface: 0.0.0.0, port: 17802
Mar 14 10:17:00 hk1 ss-manager[20994]:  2020-03-14 10:17:00 INFO: try to bind interface: 0.0.0.0, port: 17802
Mar 14 11:12:00 hk1 ss-manager[20994]:  2020-03-14 11:12:00 INFO: try to bind interface: 0.0.0.0, port: 15624
Mar 14 13:12:00 hk1 ss-manager[20994]:  2020-03-14 13:12:00 INFO: try to bind interface: 0.0.0.0, port: 17802
```

**Comment by RebelliousWhiz** [comment]
server.hk2 port 18600 is unable to access again, and I check the log it gives me the following:


```
journalctl -u ss-manager --since "14:00"
.....before it was normal log.......
Mar 15 14:01:00 hk2 ss-manager[24827]:  2020-03-15 14:00:59 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 15 14:01:00 hk2 ss-manager[24827]:  2020-03-15 14:00:59 ERROR: bind: Address already in use
Mar 15 14:01:00 hk2 ss-manager[24827]:  2020-03-15 14:00:59 ERROR: Could not bind
Mar 15 14:01:00 hk2 ss-manager[24827]:  2020-03-15 14:00:59 ERROR: port is not available, please check.
Mar 15 14:01:00 hk2 ss-manager[24827]:  2020-03-15 14:00:59 ERROR: add_sendto: Bad file descriptor
Mar 15 14:03:00 hk2 ss-manager[24827]:  2020-03-15 14:02:59 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 15 14:03:00 hk2 ss-server[759]: UDP relay enabled
Mar 15 14:03:00 hk2 ss-server[759]: initializing ciphers... aes-256-gcm
Mar 15 14:03:00 hk2 ss-server[759]: tcp server listening at 0.0.0.0:18600
Mar 15 14:03:00 hk2 ss-server[759]: udp server listening at 0.0.0.0:18600
Mar 15 14:04:00 hk2 ss-manager[24827]:  2020-03-15 14:03:59 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 15 14:04:00 hk2 ss-manager[24827]:  2020-03-15 14:03:59 ERROR: bind: Address already in use
Mar 15 14:04:00 hk2 ss-manager[24827]:  2020-03-15 14:03:59 ERROR: Could not bind
Mar 15 14:04:00 hk2 ss-manager[24827]:  2020-03-15 14:03:59 ERROR: port is not available, please check.
Mar 15 14:04:00 hk2 ss-manager[24827]:  2020-03-15 14:03:59 ERROR: add_sendto: Bad file descriptor
Mar 15 14:05:00 hk2 ss-manager[24827]:  2020-03-15 14:05:00 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 15 14:05:00 hk2 ss-server[767]: UDP relay enabled
Mar 15 14:05:00 hk2 ss-server[767]: initializing ciphers... aes-256-gcm
Mar 15 14:05:00 hk2 ss-server[767]: tcp server listening at 0.0.0.0:18600
Mar 15 14:05:00 hk2 ss-server[767]: udp server listening at 0.0.0.0:18600
Mar 15 14:05:23 hk2 ss-server[767]: server recv: Connection reset by peer
Mar 15 14:06:00 hk2 ss-manager[24827]:  2020-03-15 14:05:59 INFO: try to bind interface: 0.0.0.0, port: 18600
Mar 15 14:06:00 hk2 ss-manager[24827]:  2020-03-15 14:05:59 ERROR: bind: Address already in use
Mar 15 14:06:00 hk2 ss-manager[24827]:  2020-03-15 14:05:59 ERROR: Could not bind
Mar 15 14:06:00 hk2 ss-manager[24827]:  2020-03-15 14:05:59 ERROR: port is not available, please check.
Mar 15 14:06:00 hk2 ss-manager[24827]:  2020-03-15 14:05:59 ERROR: add_sendto: Bad file descriptor
```

**Comment by madeye** [comment]
`try to bind interface: 0.0.0.0, port: 18600` means the manager get a request to add a server on port 18600. It will failed if a server is already listening on that port.

Double check your server is configured correctly, Or you can try any other implementation, like python or rust ones.

**Comment by RebelliousWhiz** [comment]
Hi madeye,

I thought about what you said, and bind all the IP with 0.0.0.0 to server actual ethernet WAN addresses.

I will do more tests and report again.

**Comment by RebelliousWhiz** [comment]
Hi madeye,

I have tried shadowsocks-rust, shadowsocks-python (both official master, and @gyteng fork), all of them have some problems somehow.

**shadowsocks-rust (1.8.10, downloaded from CircleCI, with ss-manager udp fix)**
```
.....(normal logs)
Mar 18 17:19:50 hk3 ssmanager[12453]: [2020-03-18T09:19:50Z ERROR shadowsocks::relay::tcprelay::server] RELAY 113.92.33.92:65282 <- 13.107.42.12:443 closed with error Connection reset by peer (os error 104)
Mar 18 17:20:00 hk3 ssmanager[12453]: [2020-03-18T09:20:00Z INFO  shadowsocks::relay::tcprelay::server] shadowsocks TCP listening on 0.0.0.0:18600
Mar 18 17:20:00 hk3 ssmanager[12453]: [2020-03-18T09:20:00Z ERROR shadowsocks::relay::udprelay::server] one of UDP servers exited unexpectly, result: Err(Os { code: 98, kind: AddrInUse, message: "Address already in use" })
Mar 18 17:20:00 hk3 ssmanager[12453]: [2020-03-18T09:20:00Z ERROR shadowsocks::relay::server] one of servers exited unexpectly, result: Err(Custom { kind: Other, error: "server exited unexpectly" })
#Connection lost, then I restarted the client
Mar 18 17:21:02 hk3 ssmanager[12453]: [2020-03-18T09:21:02Z ERROR shadowsocks::relay::tcprelay::server] RELAY 113.92.33.92:65088 <- 52.114.74.44:443 closed with error Connection reset by peer (os error 104)
.....normal logs
```

**shadowsocks-python (official master, 3.0.0)**
```
.....(normal logs)
Mar 18 22:32:00 hk3 ssserver[15815]: 2020-03-18 22:32:00 ERROR    unknown command list
#This problem does not affect connection
.....(normal logs, no connection is used from this point)
Mar 19 02:25:00 hk3 ssserver[17561]: 2020-03-19 02:25:00 ERROR    server already exists at 192.168.100.110:18600
Mar 19 02:26:00 hk3 ssserver[17561]: 2020-03-19 02:26:00 ERROR    unknown command list
Mar 19 02:26:00 hk3 ssserver[17561]: 2020-03-19 02:26:00 ERROR    server already exists at 192.168.100.110:18600
Mar 19 02:27:00 hk3 ssserver[17561]: 2020-03-19 02:27:00 ERROR    unknown command list
......(endless repeat)
Mar 19 08:34:00 hk3 ssserver[17561]: 2020-03-19 08:34:00 ERROR    unknown command list
Mar 19 08:34:00 hk3 ssserver[17561]: 2020-03-19 08:34:00 ERROR    server already exists at 192.168.100.110:18600
#Unable to connect from this point
```

**shadowsocks-python (@gyteng fork, 3.0.0)**
```
....(2 mins of normal log)
Mar 18 23:13:00 hk3 ssserver[16726]: Traceback (most recent call last):
Mar 18 23:13:00 hk3 ssserver[16726]:   File "/usr/local/bin/ssserver", line 11, in <module>
Mar 18 23:13:00 hk3 ssserver[16726]:     load_entry_point('shadowsocks==3.0.0', 'console_scripts', 'ssserver')()
Mar 18 23:13:00 hk3 ssserver[16726]:   File "/usr/local/lib/python3.6/dist-packages/shadowsocks/server.py", line 54, in main
Mar 18 23:13:00 hk3 ssserver[16726]:     manager.run(config)
Mar 18 23:13:00 hk3 ssserver[16726]:   File "/usr/local/lib/python3.6/dist-packages/shadowsocks/manager.py", line 202, in run
Mar 18 23:13:00 hk3 ssserver[16726]:     Manager(config).run()
Mar 18 23:13:00 hk3 ssserver[16726]:   File "/usr/local/lib/python3.6/dist-packages/shadowsocks/manager.py", line 198, in run
Mar 18 23:13:00 hk3 ssserver[16726]:     self._loop.run()
Mar 18 23:13:00 hk3 ssserver[16726]:   File "/usr/local/lib/python3.6/dist-packages/shadowsocks/eventloop.py", line 216, in run
Mar 18 23:13:00 hk3 ssserver[16726]:     handler.handle_event(sock, fd, event)
Mar 18 23:13:00 hk3 ssserver[16726]:   File "/usr/local/lib/python3.6/dist-packages/shadowsocks/manager.py", line 133, in handle_event
Mar 18 23:13:00 hk3 ssserver[16726]:     self._send_control_data(json.dumps(ports))
Mar 18 23:13:00 hk3 ssserver[16726]:   File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
Mar 18 23:13:00 hk3 ssserver[16726]:     return _default_encoder.encode(obj)
Mar 18 23:13:00 hk3 ssserver[16726]:   File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
Mar 18 23:13:00 hk3 ssserver[16726]:     chunks = self.iterencode(o, _one_shot=True)
Mar 18 23:13:00 hk3 ssserver[16726]:   File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
Mar 18 23:13:00 hk3 ssserver[16726]:     return _iterencode(o, 0)
Mar 18 23:13:00 hk3 ssserver[16726]:   File "/usr/lib/python3.6/json/encoder.py", line 180, in default
Mar 18 23:13:00 hk3 ssserver[16726]:     o.__class__.__name__)
Mar 18 23:13:00 hk3 ssserver[16726]: TypeError: Object of type 'map' is not JSON serializable
Mar 18 23:13:00 hk3 systemd[1]: ss-manager.service: Main process exited, code=exited, status=1/FAILURE
Mar 18 23:13:00 hk3 systemd[1]: ss-manager.service: Failed with result 'exit-code'.
(dead)
```

So I switched back to shadowsocks-libev...

Due to my limited code-reading ability, I can't do much but only provide a few opinions for my disconnection problem:

1. central_server continuously sends "open port" command to nodes without knowing the port is already opened;

2. when a port restart is occurred because of 1, the client-side does know it, and it keeps connecting the server as it was nothing happened, that's why the disconnection happened;

3. to proof 2, I connected the node again, after disconnecting the node, it is working until next disconnection occurred.

I have other things that I didn't mention in the previous statement:

Initially, I have hk1 to set up as the main server, hk2 to be the node. Then I snapshot the hk2 image and use the image to create hk3. I guess this should affect much, but I will try to delete all the previously stored .shadowsocks files and SQLite databases and see if it helps.

**Comment by RebelliousWhiz** [comment]
To update, I think the problem was more like a port-opening problem rather than a problem caused by ss-manager restarting the port.

I opened a few ports according to the [Skype website](https://support.skype.com/en/faq/FA148/which-ports-need-to-be-open-to-use-skype-on-desktop), and the situation is getting better (or at least I feel it's getting better).

However, I am doing more tests to report again.

**Comment by RebelliousWhiz** [comment]
I know this problem is difficult to locate, please let me know what should I do to make you easier to identify the problem. Many thanks in advance!

Opening up the ports do help the connection on Skype, but the port restarting problem continues.

It restarted again, and cut my connection when I was in a meeting.

```
Mar 30 17:04:36 hk3 ss-server[28914]: remote recv: Connection reset by peer
Mar 30 17:05:18 hk3 ss-server[28914]: remote recv: Connection reset by peer
Mar 30 17:05:28 hk3 ss-server[28914]: remote recv: Connection reset by peer
Mar 30 17:05:45 hk3 ss-server[28914]: remote recv: Connection reset by peer
Mar 30 17:05:56 hk3 ss-server[28914]: remote recv: Connection reset by peer
(以上为正常LOG)

Mar 30 17:07:00 hk3 ss-manager[670]:  2020-03-30 17:07:00 INFO: try to bind interface: 192.168.100.110, port: 16548
Mar 30 17:07:00 hk3 ss-manager[670]:  2020-03-30 17:07:00 ERROR: bind: Address already in use
Mar 30 17:07:00 hk3 ss-manager[670]:  2020-03-30 17:07:00 ERROR: Could not bind
Mar 30 17:07:00 hk3 ss-manager[670]:  2020-03-30 17:07:00 ERROR: port is not available, please check.
Mar 30 17:07:00 hk3 ss-manager[670]:  2020-03-30 17:07:00 ERROR: add_sendto: Bad file descriptor
(这里没断）

Mar 30 17:08:58 hk3 ss-server[30296]: remote recv: Connection reset by peer
Mar 30 17:08:59 hk3 ss-server[30296]: crypto: AEAD: repeat salt detected
Mar 30 17:08:59 hk3 ss-server[30296]: failed to handshake with 119.118.27.75: authentication error
Mar 30 17:08:59 hk3 ss-server[30296]: crypto: AEAD: repeat salt detected
Mar 30 17:08:59 hk3 ss-server[30296]: failed to handshake with 150.255.3.130: authentication error
(上面的两个验证失败ip都不是我的)

Mar 30 17:09:00 hk3 ss-manager[670]:  2020-03-30 17:09:00 INFO: try to bind interface: 192.168.100.110, port: 16548
Mar 30 17:09:00 hk3 ss-server[30969]: UDP relay enabled
Mar 30 17:09:00 hk3 ss-server[30969]: initializing ciphers... aes-256-gcm
Mar 30 17:09:00 hk3 ss-server[30969]: using nameserver: 9.9.9.9,1.1.1.1,1.0.0.1
Mar 30 17:09:00 hk3 ss-server[30969]: tcp server listening at 192.168.100.110:16548
Mar 30 17:09:00 hk3 ss-server[30969]: udp server listening at 192.168.100.110:16548
Mar 30 17:09:21 hk3 ss-server[30296]: crypto: AEAD: repeat salt detected
(这里开始断了)

Mar 30 17:09:21 hk3 ss-server[30296]: failed to handshake with 122.96.131.50: authentication error
Mar 30 17:10:00 hk3 ss-manager[670]:  2020-03-30 17:10:00 INFO: try to bind interface: 192.168.100.110, port: 16548
Mar 30 17:10:00 hk3 ss-server[31169]: UDP relay enabled
Mar 30 17:10:00 hk3 ss-server[31169]: initializing ciphers... aes-256-gcm
Mar 30 17:10:00 hk3 ss-server[31169]: using nameserver: 9.9.9.9,1.1.1.1,1.0.0.1
Mar 30 17:10:00 hk3 ss-server[31169]: tcp server listening at 192.168.100.110:16548
Mar 30 17:10:00 hk3 ss-server[31169]: udp server listening at 192.168.100.110:16548
(这一分钟内都没连上)

Mar 30 17:10:31 hk3 ss-server[30296]: crypto: AEAD: repeat salt detected
Mar 30 17:10:31 hk3 ss-server[30296]: failed to handshake with 175.184.164.57: authentication error
Mar 30 17:10:36 hk3 ss-server[30296]: remote recv: Connection reset by peer
Mar 30 17:10:37 hk3 ss-server[30296]: remote recv: Connection reset by peer
Mar 30 17:10:48 hk3 ss-server[30296]: remote recv: Connection reset by peer
(又开始正常LOG)
```
I also pulled the restarting log (by pulling UDP restart log), it appears no matter what I have done, it's going to restart whenever it wants anyways...

```
Mar 28
Mar 28 00:08:54 hk3 ss-server[910]: UDP relay enabled
Mar 28 00:08:54 hk3 ss-server[913]: UDP relay enabled
Mar 28 02:12:26 hk3 ss-server[913]: UDP relay enabled
Mar 28 02:12:26 hk3 ss-server[916]: UDP relay enabled
(这天给客户调程序，4-5点才睡）
Mar 28 06:06:00 hk3 ss-server[3304]: UDP relay enabled
(没咋用，下午才起床)
Mar 28 13:41:00 hk3 ss-server[6892]: UDP relay enabled
Mar 28 13:41:00 hk3 ss-server[6895]: UDP relay enabled
Mar 28 15:13:00 hk3 ss-server[8553]: UDP relay enabled
Mar 28 15:14:00 hk3 ss-server[8564]: UDP relay enabled
Mar 28 16:05:00 hk3 ss-server[8946]: UDP relay enabled
Mar 28 16:13:00 hk3 ss-server[9093]: UDP relay enabled
Mar 28 16:16:00 hk3 ss-server[9116]: UDP relay enabled
Mar 28 16:18:00 hk3 ss-server[9122]: UDP relay enabled
Mar 28 16:21:00 hk3 ss-server[9136]: UDP relay enabled
Mar 28 16:34:00 hk3 ss-server[9202]: UDP relay enabled
Mar 28 16:59:00 hk3 ss-server[9415]: UDP relay enabled
Mar 28 17:23:00 hk3 ss-server[9618]: UDP relay enabled
Mar 28 17:41:00 hk3 ss-server[9804]: UDP relay enabled
Mar 28 18:07:00 hk3 ss-server[9965]: UDP relay enabled
Mar 28 18:29:00 hk3 ss-server[10163]: UDP relay enabled
Mar 28 19:05:00 hk3 ss-server[10397]: UDP relay enabled
Mar 28 19:29:00 hk3 ss-server[10609]: UDP relay enabled
Mar 28 19:48:00 hk3 ss-server[10782]: UDP relay enabled
Mar 28 22:28:00 hk3 ss-server[11822]: UDP relay enabled
Mar 28 22:31:00 hk3 ss-server[11825]: UDP relay enabled
Mar 28 22:34:00 hk3 ss-server[11829]: UDP relay enabled
Mar 28 22:37:00 hk3 ss-server[11833]: UDP relay enabled

Mar 29
Mar 29 01:12:00 hk3 ss-server[12977]: UDP relay enabled
Mar 29 09:11:00 hk3 ss-server[16960]: UDP relay enabled
(早上用FaceTime和朋友打了个电话，好几个小时..)
Mar 29 14:13:00 hk3 ss-server[18889]: UDP relay enabled
Mar 29 15:09:00 hk3 ss-server[19286]: UDP relay enabled
Mar 29 15:10:00 hk3 ss-server[19361]: UDP relay enabled
Mar 29 15:29:00 hk3 ss-server[19483]: UDP relay enabled
Mar 29 15:51:00 hk3 ss-server[19678]: UDP relay enabled
Mar 29 16:17:00 hk3 ss-server[19949]: UDP relay enabled
Mar 29 16:40:00 hk3 ss-server[20197]: UDP relay enabled
Mar 29 17:09:00 hk3 ss-server[20383]: UDP relay enabled
Mar 29 17:25:00 hk3 ss-server[20542]: UDP relay enabled
Mar 29 18:34:00 hk3 ss-server[21005]: UDP relay enabled
Mar 29 22:39:00 hk3 ss-server[22555]: UDP relay enabled

Mar 30
Mar 30 01:02:00 hk3 ss-server[23528]: UDP relay enabled
Mar 30 08:27:00 hk3 ss-server[27503]: UDP relay enabled
Mar 30 08:52:00 hk3 ss-server[27725]: UDP relay enabled
Mar 30 09:04:00 hk3 ss-server[27793]: UDP relay enabled
Mar 30 09:15:00 hk3 ss-server[27946]: UDP relay enabled
Mar 30 09:27:00 hk3 ss-server[28024]: UDP relay enabled
Mar 30 09:30:00 hk3 ss-server[28037]: UDP relay enabled
Mar 30 11:40:00 hk3 ss-server[28914]: UDP relay enabled
Mar 30 15:21:00 hk3 ss-server[30296]: UDP relay enabled
Mar 30 17:09:00 hk3 ss-server[30969]: UDP relay enabled
(Skype开着会，啪，断了，看着时间来抓LOG)
Mar 30 17:10:00 hk3 ss-server[31169]: UDP relay enabled
```

I am not sure when and how ss-manager received a signal to restart the port. Please let me know what should I do to help identify the problem.

Thanks again!

**Comment by RebelliousWhiz** [comment]
I have been contacting @gyteng and he tried to [fix this issue](https://github.com/shadowsocks/shadowsocks-manager/commit/14d76233b1f91b4efbb32bee63e899b8d30120a5) by modifying port restart mechanism.

I am testing to see if this problem is resolved.

**Comment by RebelliousWhiz** [comment]
I can confirm after the fix done by @gyteng, the problem is no longer exits.

This occurs because too many data were transferred through the port, and triggered the mechanism to force the port to restart.

After the fix, the high-bandwidth-usage ports still restart somehow, but other ports with normal usages are now doing fine.
