### ISSUE TITLE
Segmentation fault when using PolarSSL and UDP relay

### ISSUE THREAD

**Issue by hosiet** [shadowsocks/shadowsocks-libev#391]
When using ss-server linked against polarssl with udp relay enabled, segment fault will happen every time the connection is established:

    # ss-server -c /etc/shadowsocks-libev/config.json -v -u
    2015-09-08 14:17:54 INFO: initialize ciphers... aes-256-cfb
    2015-09-08 14:17:54 INFO: listening at *:12580
    2015-09-08 14:17:54 INFO: UDP relay enabled
    2015-09-08 14:18:29 INFO: accept a connection
    2015-09-08 14:18:29 INFO: connect to: 91.108.56.166:443
    2015-09-08 14:18:29 INFO: remote connected
    2015-09-08 14:18:32 INFO: [udp] server receive a packet
    Segmentation fault

    # ss-server -c /etc/shadowsocks-libev/config.json -v -u
    2015-09-08 14:31:15 INFO: initialize ciphers... rc4
    2015-09-08 14:31:15 INFO: listening at *:12580
    2015-09-08 14:31:15 INFO: UDP relay enabled
    2015-09-08 14:31:38 INFO: [udp] server receive a packet
    Segmentation fault

    Program received signal SIGSEGV, Segmentation fault.
    0x00007fc8368a7a05 in cipher_free () from /usr/lib/libpolarssl.so.7
    (gdb) bt
    #0  0x00007fc8368a7a05 in cipher_free () from /usr/lib/libpolarssl.so.7
    #1  0x00007fc8368a7a29 in cipher_free_ctx () from /usr/lib/libpolarssl.so.7
    #2  0x000000000040a212 in ?? ()
    #3  0x000000000040bc92 in ?? ()
    #4  0x0000000000413586 in ?? ()
    #5  0x0000000000416c0e in ?? ()
    #6  0x0000000000404f68 in ?? ()
    #7  0x00007fc835fe1b45 in __libc_start_main (main=0x4046e0, argc=5, argv=0x7ffeb43fa198, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffeb43fa188) at libc-start.c:287
    #8  0x0000000000405759 in ?? ()

I tried aes-256-cfb, aes-128-cfb and rc4 and they all crashed similarly.

The testing environment uses libpolarssl7 on Debian 8 x64. The package version is 1.3.9-2.1.
The client I used is the Android Shadowsocks app that can be found in Google Play.

**Comment by madeye** [comment]
Try the latest commit.

**Comment by hosiet** [comment]
The latest code seems to be working. Thanks.
